import type { AssessmentResult, NormalizedRequest, RequestContext } from './types.js';

let sdkChoice: any = null;
let sdkNoul: any = null;
let sdkScore: any = null;
let sdkLoaded = false;

export async function loadTypeSafePrimitives() {
  if (!sdkLoaded) {
    try {
      const sdk = await import('@typesafe-ai/sdk');
      sdkChoice = sdk.choice;
      sdkNoul = sdk.noul;
      sdkScore = sdk.score;
      sdkLoaded = true;
    } catch {
      sdkLoaded = true;
    }
  }
  return { choice: sdkChoice, noul: sdkNoul, score: sdkScore };
}

export function createBotGateBattery() {
  if (sdkNoul && sdkChoice && sdkScore) {
    return {
      is_bot: sdkNoul(
        'Evaluate whether the incoming HTTP request in `request` is generated by an automated bot, script, crawler, scraper, or headless browser, rather than a genuine human user interacting with a standard web browser.',
        {
          true: 'Clear indicators of automation, scripting libraries, automated headless execution, scraper activity, or non-human interaction patterns.',
          false: 'Natural human interactive web browser navigation.'
        }
      ),
      is_attack: sdkNoul(
        'Evaluate whether the request contains an attack payload, exploit attempt, injection, path traversal, probe for sensitive files, or vulnerability scan.',
        {
          true: 'Malicious payloads, SQLi, XSS, SSRF, command injection, path traversal, exploit probes, or sensitive credential/file hunting.',
          false: 'Safe, legitimate, benign application interaction without exploitation intent.'
        }
      ),
      is_spoofed: sdkNoul(
        'Evaluate whether the request headers exhibit spoofing or client impersonation (such as claiming a browser User-Agent while lacking standard browser headers, or conflicting platform tokens).',
        {
          true: 'Mismatched, counterfeit, or contradictory headers indicating spoofed client identity.',
          false: 'Headers are coherent and authentic for the specified client.'
        }
      ),
      traffic_type: sdkChoice(
        'Classify the primary nature of this incoming HTTP traffic.',
        {
          human: 'Legitimate human visitor navigating the website.',
          good_bot: 'Beneficial search engine indexer, feed fetcher, or uptime monitor (e.g. Googlebot, Bingbot, Slackbot).',
          bad_bot: 'Automated scraper, content scraper, spam bot, or unauthorized scraping tool.',
          attack: 'Hostile attacker executing vulnerability scans, exploit probes, or injection attacks.'
        }
      ),
      risk_level: sdkScore(
        'Rate the security and operational risk this request poses to the website or service.',
        [
          'Level 0: Safe - normal human traffic or well-behaved verified search crawler.',
          'Level 1: Low risk - minor header anomaly or benign unfamiliar crawler without malicious activity.',
          'Level 2: Suspicious - aggressive automated scraping, suspicious probes, or inconsistent headers.',
          'Level 3: Dangerous - active exploitation, injection payload, unauthorized sensitive path probe, or credential abuse.'
        ]
      )
    };
  }

  // Pure data structure fallback if SDK is not imported
  return {
    is_bot: { type: 'noul', instructions: 'Is bot?' },
    is_attack: { type: 'noul', instructions: 'Is attack?' },
    is_spoofed: { type: 'noul', instructions: 'Is spoofed?' },
    traffic_type: { type: 'choice', instructions: 'Traffic type' },
    risk_level: { type: 'score', instructions: 'Risk level' }
  };
}

/**
 * Computes Shannon entropy of a string using Uint8Array frequency table.
 * Useful for detecting obfuscated attack strings and random scanner paths.
 */
export function calculateShannonEntropy(str: string): number {
  if (!str || str.length === 0) return 0;
  const len = str.length;
  const frequencies = new Uint16Array(256);

  for (let i = 0; i < len; i++) {
    frequencies[str.charCodeAt(i) & 0xff]++;
  }

  let entropy = 0;
  for (let i = 0; i < 256; i++) {
    const count = frequencies[i];
    if (count > 0) {
      const p = count / len;
      entropy -= p * Math.log2(p);
    }
  }
  return entropy;
}

export function heuristicAssessment(
  request: NormalizedRequest,
  context: RequestContext
): AssessmentResult {
  const userAgent = (request.headers['user-agent'] || '').toLowerCase();
  const path = request.path.toLowerCase();
  const queryStr = JSON.stringify(request.query).toLowerCase();
  const bodyStr = typeof request.body === 'string' ? request.body.toLowerCase() : JSON.stringify(request.body || '').toLowerCase();
  const headersStr = JSON.stringify(request.headers).toLowerCase();
  const fullTarget = `${path} ${queryStr} ${bodyStr} ${headersStr}`;

  let botScore = 0.05;
  let attackScore = 0.02;
  let spoofScore = 0.05;

  // Good bots check
  if (context.isKnownSearchBot) {
    botScore = 0.95;
    attackScore = 0.01;
    return {
      isBotProbability: botScore,
      isAttackProbability: attackScore,
      isSpoofedProbability: 0.02,
      trafficType: 'good_bot',
      trafficTypeConfidence: 0.96,
      trafficTypeDistribution: { good_bot: 0.94, human: 0.02, bad_bot: 0.03, attack: 0.01 },
      riskScore: 0.1,
      riskConfidence: 0.95,
      riskLevelDistribution: { '0': 0.92, '1': 0.07, '2': 0.01, '3': 0.0 }
    };
  }

  // Known attack tools
  if (context.suspiciousSignatures.length > 0) {
    botScore = 0.99;
    attackScore = 0.98;
    spoofScore = 0.85;
  }

  // Common CLI / automation tools
  const cliTools = [
    'curl/', 'python-requests', 'aiohttp', 'httpx', 'wget/', 'go-http-client',
    'axios/', 'node-fetch', 'libwww-perl', 'postmanruntime', 'scrapy'
  ];
  if (cliTools.some((t) => userAgent.includes(t))) {
    botScore = Math.max(botScore, 0.92);
  }

  // Headless browsers
  if (
    userAgent.includes('headlesschrome') ||
    userAgent.includes('phantomjs') ||
    userAgent.includes('selenium') ||
    userAgent.includes('puppeteer')
  ) {
    botScore = Math.max(botScore, 0.97);
    spoofScore = Math.max(spoofScore, 0.80);
  }

  // Missing browser headers when claiming browser
  if (context.claimsBrowser && context.missingBrowserHeaders.length > 0) {
    spoofScore = Math.max(spoofScore, 0.40 + context.missingBrowserHeaders.length * 0.20);
    botScore = Math.max(botScore, 0.65);
  }

  // Common sensitive path hunting & vulnerability scanning
  const sensitivePaths = [
    '/.env',
    '/wp-login.php',
    '/wp-admin',
    '/.git',
    '/actuator',
    '/phpmyadmin',
    '/config.json',
    '/database.yml',
    '/.aws/credentials'
  ];
  if (sensitivePaths.some((p) => path.includes(p))) {
    attackScore = Math.max(attackScore, 0.85);
    botScore = Math.max(botScore, 0.80);
  }

  // Injection signatures (SQLi, XSS, Path Traversal, Command Injection, Log4j)
  const sqliSignatures = [
    "' or 1=1", '" or 1=1', 'union select', 'union all select',
    'sleep(', 'benchmark(', 'information_schema', 'select sleep'
  ];
  const xssSignatures = ['<script>', 'javascript:', '<svg onload', 'onerror=alert'];
  const traversalSignatures = ['../', '..\\', '%2e%2e%2f', '%252e%252e'];
  const cmdSignatures = ['; cat ', '| whoami', '&& id', '`whoami`', '${jndi:'];

  if (sqliSignatures.some((sig) => fullTarget.includes(sig))) {
    attackScore = Math.max(attackScore, 0.96);
    botScore = Math.max(botScore, 0.75);
  }
  if (xssSignatures.some((sig) => fullTarget.includes(sig))) {
    attackScore = Math.max(attackScore, 0.92);
  }
  if (traversalSignatures.some((sig) => fullTarget.includes(sig))) {
    attackScore = Math.max(attackScore, 0.95);
    botScore = Math.max(botScore, 0.80);
  }
  if (cmdSignatures.some((sig) => fullTarget.includes(sig))) {
    attackScore = Math.max(attackScore, 0.98);
  }

  // High entropy in query strings often signals binary shellcode or obfuscated injection
  if (queryStr.length > 30) {
    const entropy = calculateShannonEntropy(queryStr);
    if (entropy > 4.6 && attackScore < 0.6) {
      attackScore = Math.max(attackScore, 0.65);
    }
  }

  // Determine traffic category
  let trafficType: 'human' | 'good_bot' | 'bad_bot' | 'attack' = 'human';
  if (attackScore >= 0.70) {
    trafficType = 'attack';
  } else if (botScore >= 0.60) {
    trafficType = 'bad_bot';
  }

  let calculatedRisk = attackScore * 2.8 + botScore * 0.7;
  if (calculatedRisk > 3.0) calculatedRisk = 3.0;

  const typeDistribution: Record<string, number> = {
    human: trafficType === 'human' ? 0.85 : 0.05,
    good_bot: 0.02,
    bad_bot: trafficType === 'bad_bot' ? 0.80 : 0.10,
    attack: trafficType === 'attack' ? 0.90 : 0.05
  };
  const total = Object.values(typeDistribution).reduce((a, b) => a + b, 0);
  for (const k of Object.keys(typeDistribution)) {
    typeDistribution[k] = Math.round((typeDistribution[k] / total) * 100) / 100;
  }

  return {
    isBotProbability: Math.min(1.0, Math.round(botScore * 100) / 100),
    isAttackProbability: Math.min(1.0, Math.round(attackScore * 100) / 100),
    isSpoofedProbability: Math.min(1.0, Math.round(spoofScore * 100) / 100),
    trafficType,
    trafficTypeConfidence: 0.88,
    trafficTypeDistribution: typeDistribution,
    riskScore: Math.round(calculatedRisk * 100) / 100,
    riskConfidence: 0.85,
    riskLevelDistribution: {
      '0': calculatedRisk < 0.5 ? 0.9 : 0.05,
      '1': calculatedRisk >= 0.5 && calculatedRisk < 1.5 ? 0.8 : 0.1,
      '2': calculatedRisk >= 1.5 && calculatedRisk < 2.5 ? 0.85 : 0.1,
      '3': calculatedRisk >= 2.5 ? 0.9 : 0.05
    }
  };
}
