"""TypeSafe System One battery definitions and zero-dep heuristic assessment for traffic-guard."""

from __future__ import annotations

import json
import math
from collections import Counter
from dataclasses import dataclass, field
from typing import Any

from .normalizer import NormalizedRequest, RequestContext

try:
    from typesafe_sdk import Choice, Noul, NoulCriteria, Score
    HAS_TYPESAFE = True
except ImportError:
    HAS_TYPESAFE = False
    Choice = Noul = NoulCriteria = Score = None  # type: ignore


@dataclass
class AssessmentResult:
    is_bot_probability: float
    is_attack_probability: float
    is_spoofed_probability: float
    traffic_type: str
    traffic_type_confidence: float
    traffic_type_distribution: dict[str, float] = field(default_factory=dict)
    risk_score: float = 0.0
    risk_confidence: float = 0.8
    risk_level_distribution: dict[str, float] = field(default_factory=dict)


def create_bot_gate_battery() -> dict[str, Any]:
    if HAS_TYPESAFE and Noul is not None and Choice is not None and Score is not None:
        return {
            "is_bot": Noul(
                instructions=(
                    "Evaluate whether the incoming HTTP request in `request` is generated by an automated bot, "
                    "script, crawler, scraper, or headless browser, rather than a genuine human user interacting with a standard web browser."
                ),
                criteria=NoulCriteria(
                    true="Clear indicators of automation, scripting libraries, automated headless execution, scraper activity, or non-human interaction patterns.",
                    false="Natural human interactive web browser navigation.",
                ),
            ),
            "is_attack": Noul(
                instructions=(
                    "Evaluate whether the request contains an attack payload, exploit attempt, injection, path traversal, "
                    "probe for sensitive files, or vulnerability scan."
                ),
                criteria=NoulCriteria(
                    true="Malicious payloads, SQLi, XSS, SSRF, command injection, path traversal, exploit probes, or sensitive credential/file hunting.",
                    false="Safe, legitimate, benign application interaction without exploitation intent.",
                ),
            ),
            "is_spoofed": Noul(
                instructions=(
                    "Evaluate whether the request headers exhibit spoofing or client impersonation "
                    "(such as claiming a browser User-Agent while lacking standard browser headers, or conflicting platform tokens)."
                ),
                criteria=NoulCriteria(
                    true="Mismatched, counterfeit, or contradictory headers indicating spoofed client identity.",
                    false="Headers are coherent and authentic for the specified client.",
                ),
            ),
            "traffic_type": Choice(
                instructions="Classify the primary nature of this incoming HTTP traffic.",
                criteria={
                    "human": "Legitimate human visitor navigating the website.",
                    "good_bot": "Beneficial search engine indexer, feed fetcher, or uptime monitor (e.g. Googlebot, Bingbot, Slackbot).",
                    "bad_bot": "Automated scraper, content scraper, spam bot, or unauthorized scraping tool.",
                    "attack": "Hostile attacker executing vulnerability scans, exploit probes, or injection attacks.",
                },
            ),
            "risk_level": Score(
                instructions="Rate the security and operational risk this request poses to the website or service.",
                criteria=[
                    "Level 0: Safe - normal human traffic or well-behaved verified search crawler.",
                    "Level 1: Low risk - minor header anomaly or benign unfamiliar crawler without malicious activity.",
                    "Level 2: Suspicious - aggressive automated scraping, suspicious probes, or inconsistent headers.",
                    "Level 3: Dangerous - active exploitation, injection payload, unauthorized sensitive path probe, or credential abuse.",
                ],
            ),
        }

    return {
        "is_bot": {"type": "noul", "instructions": "Is bot?"},
        "is_attack": {"type": "noul", "instructions": "Is attack?"},
        "is_spoofed": {"type": "noul", "instructions": "Is spoofed?"},
        "traffic_type": {"type": "choice", "instructions": "Traffic type"},
        "risk_level": {"type": "score", "instructions": "Risk level"},
    }


def calculate_shannon_entropy(s: str) -> float:
    """Calculate Shannon entropy of a string to detect encoded or random scanner payloads."""
    if not s:
        return 0.0
    length = len(s)
    counts = Counter(s)
    entropy = 0.0
    for count in counts.values():
        p = count / length
        entropy -= p * math.log2(p)
    return entropy


def heuristic_assessment(
    request: NormalizedRequest,
    context: RequestContext,
) -> AssessmentResult:
    user_agent = request.headers.get("user-agent", "").lower()
    path = request.path.lower()
    query_str = json.dumps(request.query).lower()
    body_str = (
        request.body.lower()
        if isinstance(request.body, str)
        else json.dumps(request.body or "").lower()
    )
    headers_str = json.dumps(request.headers).lower()
    full_target = f"{path} {query_str} {body_str} {headers_str}"

    bot_score = 0.05
    attack_score = 0.02
    spoof_score = 0.05

    if context.is_known_search_bot:
        return AssessmentResult(
            is_bot_probability=0.95,
            is_attack_probability=0.01,
            is_spoofed_probability=0.02,
            traffic_type="good_bot",
            traffic_type_confidence=0.96,
            traffic_type_distribution={"good_bot": 0.94, "human": 0.02, "bad_bot": 0.03, "attack": 0.01},
            risk_score=0.1,
            risk_confidence=0.95,
            risk_level_distribution={"0": 0.92, "1": 0.07, "2": 0.01, "3": 0.0},
        )

    if context.suspicious_signatures:
        bot_score = 0.99
        attack_score = 0.98
        spoof_score = 0.85

    cli_tools = [
        "curl/", "python-requests", "aiohttp", "httpx", "wget/", "go-http-client",
        "axios/", "node-fetch", "libwww-perl", "postmanruntime", "scrapy"
    ]
    if any(t in user_agent for t in cli_tools):
        bot_score = max(bot_score, 0.92)

    if any(h in user_agent for h in ("headlesschrome", "phantomjs", "selenium", "puppeteer")):
        bot_score = max(bot_score, 0.97)
        spoof_score = max(spoof_score, 0.80)

    if context.claims_browser and context.missing_browser_headers:
        spoof_score = max(spoof_score, 0.40 + len(context.missing_browser_headers) * 0.20)
        bot_score = max(bot_score, 0.65)

    sensitive_paths = [
        "/.env", "/wp-login.php", "/wp-admin", "/.git", "/actuator",
        "/phpmyadmin", "/config.json", "/database.yml", "/.aws/credentials"
    ]
    if any(p in path for p in sensitive_paths):
        attack_score = max(attack_score, 0.85)
        bot_score = max(bot_score, 0.80)

    sqli = [
        "' or 1=1", '" or 1=1', "union select", "union all select",
        "sleep(", "benchmark(", "information_schema", "select sleep"
    ]
    xss = ["<script>", "javascript:", "<svg onload", "onerror=alert"]
    traversal = ["../", "..\\", "%2e%2e%2f", "%252e%252e"]
    cmd = ["; cat ", "| whoami", "&& id", "`whoami`", "${jndi:"]

    if any(s in full_target for s in sqli):
        attack_score = max(attack_score, 0.96)
        bot_score = max(bot_score, 0.75)
    if any(s in full_target for s in xss):
        attack_score = max(attack_score, 0.92)
    if any(s in full_target for s in traversal):
        attack_score = max(attack_score, 0.95)
        bot_score = max(bot_score, 0.80)
    if any(s in full_target for s in cmd):
        attack_score = max(attack_score, 0.98)

    if len(query_str) > 30:
        entropy = calculate_shannon_entropy(query_str)
        if entropy > 4.6 and attack_score < 0.6:
            attack_score = max(attack_score, 0.65)

    traffic_type = "human"
    if attack_score >= 0.70:
        traffic_type = "attack"
    elif bot_score >= 0.60:
        traffic_type = "bad_bot"

    calculated_risk = min(3.0, attack_score * 2.8 + bot_score * 0.7)

    return AssessmentResult(
        is_bot_probability=min(1.0, round(bot_score, 2)),
        is_attack_probability=min(1.0, round(attack_score, 2)),
        is_spoofed_probability=min(1.0, round(spoof_score, 2)),
        traffic_type=traffic_type,
        traffic_type_confidence=0.88,
        traffic_type_distribution={
            "human": 0.85 if traffic_type == "human" else 0.05,
            "good_bot": 0.02,
            "bad_bot": 0.80 if traffic_type == "bad_bot" else 0.10,
            "attack": 0.90 if traffic_type == "attack" else 0.05,
        },
        risk_score=round(calculated_risk, 2),
        risk_confidence=0.85,
        risk_level_distribution={
            "0": 0.9 if calculated_risk < 0.5 else 0.05,
            "1": 0.8 if 0.5 <= calculated_risk < 1.5 else 0.1,
            "2": 0.85 if 1.5 <= calculated_risk < 2.5 else 0.1,
            "3": 0.9 if calculated_risk >= 2.5 else 0.05,
        },
    )
